name: Deploy to Server

on:
  push:
    branches:
      - main  # o cualquier rama en la que desees activar este pipeline

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'  # version LTS

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm test

    - name: Build Angular application
      run: npm run build

    - name: Deploy to server
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        HOST: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USERNAME }}
        DEPLOY_PATH: ${{ secrets.DEPLOY_PATH }}
      run: |
        echo "Deploying to server..."
        mkdir -p ~/.ssh
        echo "$SSH_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh -o StrictHostKeyChecking=no $USERNAME@$HOST "mkdir -p $DEPLOY_PATH"
        rsync -avz --delete ./dist/suma-app/browser $USERNAME@$HOST:$DEPLOY_PATH
        ssh $USERNAME@$HOST 'sudo systemctl restart nginx'

